
title: OCTA-RV dataset
page-top-title: OCTA-RV
top-section-bg-text: WS-SAM: Self-Prompt SAM with Wavelet Space Domain for OCTA vessel segmentation
home-subtitle: Datatset Description
copyright-text: '&copy; Units: Qufu Normal University Computer College. Email: mafei0603@163.com.'
